spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devices
    username: your_username
    password: your_password
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  security:
    jwt:
      secret: your-secret-key
      expiration: 3600

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080
