spring:
  datasource:
    url: jdbc:postgresql://smart-home-homes-postgresql.default:5432/smart_home
    username: your_username
    password: your_password
    hikari:
      allow-pool-suspension: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        boot.allow_jdbc_metadata_access: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: your-secret-key
      expiration: 3600

server:
  port: 8080
