### create home for user-1
POST http://localhost:8080/homes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MjUyMDU2NTksImV4cCI6MTc1Njc0MTY1OSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoidXNlci0xIn0.KSz5Y27TIApz3Og6J_xc0NposG-NjUsQlehNuJxlmRE
Content-Type: application/json

{
  "homeName": "Test user-1 home"
}

### read homes list for user-1
GET http://localhost:8080/homes
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJPbmxpbmUgSldUIEJ1aWxkZXIiLCJpYXQiOjE3MjUyMDU2NTksImV4cCI6MTc1Njc0MTY1OSwiYXVkIjoid3d3LmV4YW1wbGUuY29tIiwic3ViIjoidXNlci0xIn0.KSz5Y27TIApz3Og6J_xc0NposG-NjUsQlehNuJxlmRE
Content-Type: application/json

### check access to home
POST http://localhost:8080/service/validate-access
Content-Type: application/json

{
  "userId": "user-1",
  "homeId": "home-01"
}

### check access to not exist home
POST http://localhost:8080/service/validate-access
Content-Type: application/json

{
  "userId": "user-1",
  "homeId": "home-200"
}

### check not exist user access to home
POST http://localhost:8080/service/validate-access
Content-Type: application/json

{
  "userId": "user-22",
  "homeId": "home-01"
}

### check homes list for user
GET http://localhost:8080/service/homes?userId=user-1


