@startuml
!define RELATIVE_INCLUDE true

!includeurl C4/C4_Context.puml

Person(user, "Владелец дома", "Пользователь, который управляет системой отопления через веб-интерфейс")

System(system, "Система отопления", "Управляет отоплением дома, включая контроль и мониторинг температуры")

System_Ext(webui, "Веб-интерфейс", "Позволяет владельцам домов взаимодействовать с системой отопления")
System_Ext(sensors, "Датчики температуры", "Передают текущие данные о температуре в систему отопления")
System_Ext(heatingDevices, "Устройства отопления", "Отапливают помещения")

Rel(user, webui, "Использует", "HTTP/HTTPS")
Rel(webui, system, "Отправляет запросы API", "REST API")
Rel(system, sensors, "Запрашивает данные о температуре", "REST API")
Rel(system, heatingDevices, "Управляет отоплением", "REST API")

@enduml
