name: ci

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: docker-compose up -d --build

      - name: Wait for services to be healthy
        run: |
          for i in {1..10}; do
            if [ $(docker-compose ps -q | xargs docker inspect -f '{{ .State.Health.Status }}' | grep -c unhealthy) -eq 0 ]; then
              echo "All services are healthy!"
              exit 0
            fi
            echo "Waiting for services to be healthy..."
            sleep 10
          done
          echo "Services did not become healthy in time"
          docker-compose logs
          exit 1

      - name: Shut down services
        run: docker-compose down

#      -
#        name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}
#      -
#        name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          platforms: linux/amd64,linux/arm64
#          context: smart-home-monolith
#          push: true
#          tags: ghcr.io/yandex-practicum/architecture-sprint-3:latest
#          cache-from: type=gha
#          cache-to: type=gha,mode=max
